import React from 'react';
import NavBar from '../../components/NavBar/NavBar';
import RecipeCard from '../../components/RecipeCard/RecipeCard';
import Grid from '@mui/material/Unstable_Grid2';
import { faker } from '@faker-js/faker';
import { useGetRecipes } from '../../hooks/useRecipes';

const Home = () => {
  const [query, setQuery] = React.useState('');
  const { error, loading, data } = useGetRecipes('chicken');

  const onChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    event.preventDefault();
    setQuery(event.target.value);
    console.log(error);
    console.log(loading);
    console.log(data);
  };

  const onClick = (event: React.MouseEvent<HTMLButtonElement>) => {
    event.preventDefault();
    console.log(query);
  };

  return (
    <div>
      <NavBar onChange={onChange} onClick={onClick} />
      <Grid
        container
        spacing={1}
        justifyContent="space-around"
        alignContent="center"
        mt={3}
      >
        <RecipeCard
          label={faker.commerce.product()}
          image={faker.image.food()}
          ingredients={[
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage()
          ]}
        />
        <RecipeCard
          label={faker.commerce.product()}
          image={faker.image.food()}
          ingredients={[
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage()
          ]}
        />
        <RecipeCard
          label={faker.commerce.product()}
          image={faker.image.food()}
          ingredients={[
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage()
          ]}
        />
        <RecipeCard
          label={faker.commerce.product()}
          image={faker.image.food()}
          ingredients={[
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage()
          ]}
        />
        <RecipeCard
          label={faker.commerce.product()}
          image={faker.image.food()}
          ingredients={[
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage()
          ]}
        />
        <RecipeCard
          label={faker.commerce.product()}
          image={faker.image.food()}
          ingredients={[
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage()
          ]}
        />
        <RecipeCard
          label={faker.commerce.product()}
          image={faker.image.food()}
          ingredients={[
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage()
          ]}
        />
        <RecipeCard
          label={faker.commerce.product()}
          image={faker.image.food()}
          ingredients={[
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage()
          ]}
        />
        <RecipeCard
          label={faker.commerce.product()}
          image={faker.image.food()}
          ingredients={[
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage()
          ]}
        />
        <RecipeCard
          label={faker.commerce.product()}
          image={faker.image.food()}
          ingredients={[
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage()
          ]}
        />
        <RecipeCard
          label={faker.commerce.product()}
          image={faker.image.food()}
          ingredients={[
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage()
          ]}
        />
        <RecipeCard
          label={faker.commerce.product()}
          image={faker.image.food()}
          ingredients={[
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage()
          ]}
        />
        <RecipeCard
          label={faker.commerce.product()}
          image={faker.image.food()}
          ingredients={[
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage()
          ]}
        />
        <RecipeCard
          label={faker.commerce.product()}
          image={faker.image.food()}
          ingredients={[
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage()
          ]}
        />
        <RecipeCard
          label={faker.commerce.product()}
          image={faker.image.food()}
          ingredients={[
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage()
          ]}
        />
        <RecipeCard
          label={faker.commerce.product()}
          image={faker.image.food()}
          ingredients={[
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage()
          ]}
        />
        <RecipeCard
          label={faker.commerce.product()}
          image={faker.image.food()}
          ingredients={[
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage()
          ]}
        />
        <RecipeCard
          label={faker.commerce.product()}
          image={faker.image.food()}
          ingredients={[
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage()
          ]}
        />
        <RecipeCard
          label={faker.commerce.product()}
          image={faker.image.food()}
          ingredients={[
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage(),
            faker.git.commitMessage()
          ]}
        />
      </Grid>
    </div>
  );
};

export default Home;
